# This is a basic workflow that is manually triggered
name: Update M3U Playlists

# Trigger the workflow on push or a daily schedule
on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering from the GitHub Actions interface

jobs:
  update_m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run the Python script
      run: |
        python m3u.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add cn.m3u
        git commit -m "Update M3U Playlist"
        git push
